### ISSUE TITLE
eprosima::fastcdr::exception::BadParamException: Unexpected byte value in Cdr::deserialize(bool), expected 0 or 1 [4298]

### ISSUE THREAD

**Issue by TSC21** [eProsima/Fast-CDR#41]
While running an instance of a Fast-CDR deserialisation in a micro-RTPS bridge, I get the following error:
```
terminate called after throwing an instance of 'eprosima::fastcdr::exception::BadParamException'
  what():  Unexpected byte value in Cdr::deserialize(bool), expected 0 or 1
Aborted (core dumped)
```
It comes to my attention that this happens with certain messages that contain boolean fields, though I am not sure of what's actually causing this to happen, as the boolean fields seem to be properly initialised on the client side.

The agent code is generated using https://github.com/PX4/px4_ros_com/blob/master/msg/templates/microRTPS_agent.cpp.template.

@richiprosima @MiguelCompany any inputs you can give here? Thanks in advance!

**Comment by TSC21** [comment]
@richiware any input you can give here?

**Comment by richiware** [comment]
Currently FastCDR expects 0 or 1 values when deserializing a boolean. But MicroCDR doesn't have this restriction. It serializes any value coming in the boolean field. Make sure, before serializing your structure on the client side, all boolean fields contains value 0 or 1.

**Comment by TSC21** [comment]
@richiware thanks! To make sure that the boolean fields are correctly set, maybe doing a check right before the serialisation makes sense?

**Comment by richiware** [comment]
Yes, make sense. Check the value and if it is greater than 0, set a 1.

**Comment by richiware** [comment]
Depends on how your data model treats the booleans. There are people that treat any value different from 0 as a True boolean value.

**Comment by TSC21** [comment]
@richiware we can close this. I will drop feedback on this as soon as possible. Thanks!

**Comment by TSC21** [comment]
@richiware @richiprosima I continue to run into this problem and I have already confirmed that the client side is serializing a properly initialised boolean filed, while on the agent side I am not sure that is the case. If I run the agent side with `gdb`, I am able to get something like this (for a `vehicle_gps_position` uORB msg serialized - corresponding to a `px4_msgs/VehicleGpsPosition` msg with the same IDL and msg fomat, just changing the namespace):

```gdb
terminate called after throwing an instance of 'eprosima::fastcdr::exception::BadParamException'
  what():  Unexpected byte value in Cdr::deserialize(bool), expected 0 or 1

Thread 1 "micrortps_agent" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff69a8801 in __GI_abort () at abort.c:79
#2  0x00007ffff6ffd957 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff7003ab6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff7003af1 in std::terminate() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff7003d24 in __cxa_throw ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff7522255 in eprosima::fastcdr::Cdr::deserialize(bool&) ()
   from /opt/ros/crystal/lib/libfastcdr.so.1
#7  0x0000555555583c6b in eprosima::fastcdr::Cdr::operator>> (
    bool_t=@0x7fffffffd0f0: false, this=0x7fffffffd050)
    at /opt/ros/crystal/include/fastcdr/Cdr.h:545
#8  px4_msgs::msg::dds_::VehicleGpsPosition_::deserialize (
    this=0x7fffffffd0a0, dcdr=...)
    at /home/nuno/PX4/px4_ros_com_ros2/src/px4_ros_com/src/micrortps_agent/VehicleGpsPosition_.cpp:431
#9  0x0000555555572922 in RtpsTopics::publish (this=0x5555557d3340 <topics>, 
    topic_ID=<optimised out>, data_buffer=0x7fffffffd2b0 "\300\243\356\a", 
    len=1024)
    at /home/nuno/PX4/px4_ros_com_ros2/src/px4_ros_com/src/micrortps_agent/RtpsTopics.cpp:401
#10 0x000055555555f969 in main (argc=<optimised out>, argv=<optimised out>)
---Type <return> to continue, or q <return> to quit---
   home/nuno/PX4/px4_ros_com_ros2/src/px4_ros_com/src/micrortps_agent/microRTPS_agent.cpp:254
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff69a8801 in __GI_abort () at abort.c:79
#2  0x00007ffff6ffd957 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff7003ab6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff7003af1 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff7003d24 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff7522255 in eprosima::fastcdr::Cdr::deserialize(bool&) () from /opt/ros/crystal/lib/libfastcdr.so.1
#7  0x0000555555583c6b in eprosima::fastcdr::Cdr::operator>> (bool_t=@0x7fffffffd0f0: false, this=0x7fffffffd050)
    at /opt/ros/crystal/include/fastcdr/Cdr.h:545
#8  px4_msgs::msg::dds_::VehicleGpsPosition_::deserialize (this=0x7fffffffd0a0, dcdr=...)
    at /home/nuno/PX4/px4_ros_com_ros2/src/px4_ros_com/src/micrortps_agent/VehicleGpsPosition_.cpp:431
#9  0x0000555555572922 in RtpsTopics::publish (this=0x5555557d3340 <topics>, topic_ID=<optimised out>, data_buffer=0x7fffffffd2b0 "\300\243\356\a", 
    len=1024) at /home/nuno/PX4/px4_ros_com_ros2/src/px4_ros_com/src/micrortps_agent/RtpsTopics.cpp:401
#10 0x000055555555f969 in main (argc=<optimised out>, argv=<optimised out>)
    at /home/nuno/PX4/px4_ros_com_ros2/src/px4_ros_com/src/micrortps_agent/microRTPS_agent.cpp:254
```
Can you provide some insights on what can actually be causing this error and how to debug it? Thank you very much in advance for your time.

**Comment by TSC21** [comment]
For a term of comparison, here's how the client serialises:
```c++
void vehicle_gps_position_::serialize(eprosima::fastcdr::Cdr &scdr) const
{
    scdr << m_timestamp_;
    scdr << m_lat_;
    scdr << m_lon_;
    scdr << m_alt_;
    scdr << m_alt_ellipsoid_;
    scdr << m_s_variance_m_s_;
    scdr << m_c_variance_rad_;
    scdr << m_fix_type_;
    scdr << m_eph_;
    scdr << m_epv_;
    scdr << m_hdop_;
    scdr << m_vdop_;
    scdr << m_noise_per_ms_;
    scdr << m_jamming_indicator_;
    scdr << m_vel_m_s_;
    scdr << m_vel_n_m_s_;
    scdr << m_vel_e_m_s_;
    scdr << m_vel_d_m_s_;
    scdr << m_cog_rad_;
    scdr << m_vel_ned_valid_;
    scdr << m_timestamp_time_relative_;
    scdr << m_time_utc_usec_;
    scdr << m_satellites_used_;
    scdr << m_heading_;
    scdr << m_heading_offset_;
}
```
and here's how the agent deserialises:
```c++
void px4_msgs::msg::dds_::VehicleGpsPosition_::deserialize(eprosima::fastcdr::Cdr &dcdr)
{
    dcdr >> m_timestamp_;
    dcdr >> m_lat_;
    dcdr >> m_lon_;
    dcdr >> m_alt_;
    dcdr >> m_alt_ellipsoid_;
    dcdr >> m_s_variance_m_s_;
    dcdr >> m_c_variance_rad_;
    dcdr >> m_fix_type_;
    dcdr >> m_eph_;
    dcdr >> m_epv_;
    dcdr >> m_hdop_;
    dcdr >> m_vdop_;
    dcdr >> m_noise_per_ms_;
    dcdr >> m_jamming_indicator_;
    dcdr >> m_vel_m_s_;
    dcdr >> m_vel_n_m_s_;
    dcdr >> m_vel_e_m_s_;
    dcdr >> m_vel_d_m_s_;
    dcdr >> m_cog_rad_;
    dcdr >> m_vel_ned_valid_;
    dcdr >> m_timestamp_time_relative_;
    dcdr >> m_time_utc_usec_;
    dcdr >> m_satellites_used_;
    dcdr >> m_heading_;
    dcdr >> m_heading_offset_;
}
```

**Comment by TSC21** [comment]
@richiware nevermind. It turns out the problem was that the fields of the messages were being sorted before serialization, and as on the agent side that wasn't expected, the order of deserialization was completely altered. The solution is presented in https://github.com/PX4/Firmware/pull/12025.
